import { ProjectStats } from './index.js';
import process from 'process';
import path from 'path';

export function generateHtmlReport(stats: ProjectStats): string {
    const isSafetyAvailable = !!stats.typescriptSafety;
    const isComplexityAvailable = !!stats.codeComplexity;
    
    // Calculate color classes based on thresholds
    const typeCoverageVal = isSafetyAvailable ? parseFloat(stats.typescriptSafety!.avgTypeCoverage) : 0;
    const typeCoverageClass = typeCoverageVal < 80 ? 'warning' : 'success';
    
    const safetyScoreVal = isSafetyAvailable ? stats.typescriptSafety!.avgTypeSafetyScore : 0;
    const safetyScoreClass = safetyScoreVal < 80 ? 'warning' : 'success';

    const avgComplexityVal = isComplexityAvailable ? parseFloat(stats.codeComplexity!.avgComplexity) : 0;
    const avgComplexityClass = avgComplexityVal > 5 ? 'warning' : 'success';

    const maxComplexityVal = isComplexityAvailable ? stats.codeComplexity!.maxComplexity : 0;
    const maxComplexityClass = maxComplexityVal > 15 ? 'danger' : 'success';

    const complexFilesVal = isComplexityAvailable ? stats.codeComplexity!.complexFiles : 0;
    const complexFilesClass = complexFilesVal > 0 ? 'danger' : 'success';

    const generationDate = new Date();

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Detailed TypeScript and JavaScript static analysis report generated by ts-analyzer. Includes metrics for type safety, type coverage, cyclomatic complexity, duplicate code, and structural anti-patterns.">
    <meta name="keywords" content="TypeScript, JavaScript, static analysis, code quality, type coverage, cyclomatic complexity, code smells, AST analysis">
    <meta name="robots" content="index, follow">
    <meta name="author" content="ts-analyzer">
    
    <!-- Open Graph Metadata -->
    <meta property="og:title" content="Code Quality & Type Safety Analysis Report | ts-analyzer">
    <meta property="og:description" content="TypeScript/JavaScript static analysis dashboard. Review type coverage, cyclomatic complexity, duplicate lines, and anti-patterns.">
    <meta property="og:type" content="website">
    
    <title>Code Quality & Type Safety Analysis Report | ts-analyzer</title>
    
    <!-- Google Fonts Inter -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    
    <style>
        :root {
            --primary: #4f46e5;
            --primary-dark: #3730a3;
            --primary-light: rgba(79, 70, 229, 0.1);
            --bg-main: #f8fafc;
            --bg-card: #ffffff;
            --text-main: #0f172a;
            --text-muted: #64748b;
            --border: #e2e8f0;
            
            --success: #28a745;
            --success-bg: #ecfdf5;
            --success-text: #065f46;
            
            --warning: #ffc107;
            --warning-bg: #fffbeb;
            --warning-text: #92400e;
            
            --danger: #dc3545;
            --danger-bg: #fef2f2;
            --danger-text: #991b1b;
        }

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background-color: var(--bg-main);
            color: var(--text-main);
            line-height: 1.5;
            padding: 40px 20px;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
        }

        /* Header design with dynamic indigo gradient */
        header {
            background: linear-gradient(135deg, var(--primary) 0%, #312e81 100%);
            color: white;
            padding: 40px;
            border-radius: 16px;
            margin-bottom: 40px;
            box-shadow: 0 10px 25px -5px rgba(79, 70, 229, 0.2);
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-wrap: wrap;
            gap: 20px;
        }

        header h1 {
            font-size: 32px;
            font-weight: 800;
            letter-spacing: -0.025em;
        }

        header .meta {
            font-size: 14px;
            background: rgba(255, 255, 255, 0.15);
            padding: 8px 16px;
            border-radius: 9999px;
            backdrop-filter: blur(4px);
            border: 1px solid rgba(255, 255, 255, 0.2);
        }

        main {
            display: flex;
            flex-direction: column;
            gap: 40px;
        }

        section {
            background: var(--bg-card);
            border-radius: 16px;
            border: 1px solid var(--border);
            padding: 30px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.02);
        }

        h2 {
            font-size: 22px;
            font-weight: 700;
            color: var(--text-main);
            margin-bottom: 24px;
            letter-spacing: -0.02em;
            border-left: 4px solid var(--primary);
            padding-left: 12px;
        }

        /* Grid dashboard cards */
        .grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
            gap: 24px;
        }

        .card {
            background: var(--bg-card);
            padding: 24px;
            border-radius: 12px;
            border: 1px solid var(--border);
            box-shadow: 0 1px 3px rgba(0,0,0,0.05);
            transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);
            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }

        .card:hover {
            transform: translateY(-4px);
            box-shadow: 0 12px 20px -8px rgba(0, 0, 0, 0.08);
            border-color: rgba(79, 70, 229, 0.3);
        }

        .card h3 {
            font-size: 13px;
            font-weight: 600;
            color: var(--text-muted);
            text-transform: uppercase;
            letter-spacing: 0.05em;
            margin-bottom: 12px;
        }

        .card .value {
            font-size: 36px;
            font-weight: 800;
            color: var(--text-main);
            line-height: 1.1;
        }

        .card .value.text-primary { color: var(--primary); }
        .card .value.text-success { color: var(--success); }
        .card .value.text-warning { color: var(--warning); }
        .card .value.text-danger { color: var(--danger); }

        /* Progress bars */
        .progress-container {
            margin-top: 16px;
            width: 100%;
        }

        .progress-bar {
            width: 100%;
            background-color: var(--border);
            border-radius: 9999px;
            height: 10px;
            overflow: hidden;
        }

        .progress {
            height: 100%;
            border-radius: 9999px;
            transition: width 0.8s ease-in-out;
        }

        .progress.success { background-color: var(--success); }
        .progress.warning { background-color: var(--warning); }
        .progress.danger { background-color: var(--danger); }

        /* Table styles */
        .table-responsive {
            width: 100%;
            overflow-x: auto;
            border-radius: 12px;
            border: 1px solid var(--border);
            box-shadow: 0 1px 3px rgba(0,0,0,0.02);
        }

        table {
            width: 100%;
            border-collapse: collapse;
            text-align: left;
        }

        th, td {
            padding: 16px 20px;
        }

        th {
            background-color: #f1f5f9;
            font-weight: 600;
            color: #475569;
            font-size: 14px;
            border-bottom: 1px solid var(--border);
        }

        td {
            background-color: var(--bg-card);
            border-bottom: 1px solid var(--border);
            font-size: 15px;
        }

        tr:last-child td {
            border-bottom: none;
        }

        tr:hover td {
            background-color: #f8fafc;
        }

        .extension-badge {
            font-family: monospace;
            background: #f1f5f9;
            padding: 4px 8px;
            border-radius: 6px;
            font-weight: 600;
            color: #334155;
        }

        /* Status indicators */
        .badge {
            display: inline-flex;
            align-items: center;
            padding: 4px 12px;
            border-radius: 9999px;
            font-size: 12px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.02em;
        }

        .badge.success { background-color: var(--success-bg); color: var(--success-text); }
        .badge.warning { background-color: var(--warning-bg); color: var(--warning-text); }
        .badge.danger { background-color: var(--danger-bg); color: var(--danger-text); }

        footer {
            margin-top: 60px;
            text-align: center;
            color: var(--text-muted);
            font-size: 14px;
            padding: 30px 0;
            border-top: 1px solid var(--border);
        }

        footer a {
            color: var(--primary);
            text-decoration: none;
            font-weight: 600;
            transition: color 0.15s ease;
        }

        footer a:hover {
            color: var(--primary-dark);
            text-decoration: underline;
        }
    </style>

    <!-- JSON-LD Structured Data Schema for Google indexing -->
    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "TechArticle",
      "headline": "TypeScript and JavaScript Code Quality Analysis Report",
      "description": "Static code analysis report displaying type coverage, safety rating, and complexity metrics.",
      "dateCreated": "${generationDate.toISOString()}",
      "author": {
        "@type": "SoftwareApplication",
        "name": "ts-analyzer",
        "applicationCategory": "DeveloperApplication",
        "operatingSystem": "Cross-platform"
      }
    }
    </script>
</head>
<body>
    <div class="container">
        <header>
            <div>
                <h1>TS Analyzer Report</h1>
            </div>
            <div class="meta">
                Generated: <time datetime="${generationDate.toISOString()}">${generationDate.toLocaleString()}</time>
            </div>
        </header>

        <main>
            <!-- Project Summary -->
            <section aria-labelledby="summary-heading">
                <h2 id="summary-heading">Project Summary</h2>
                <div class="grid">
                    <div class="card">
                        <h3>Total Files</h3>
                        <div class="value text-primary">${stats.formatNumber(stats.files)}</div>
                    </div>
                    <div class="card">
                        <h3>Total Lines</h3>
                        <div class="value">${stats.formatNumber(stats.totalLines)}</div>
                    </div>
                    <div class="card">
                        <h3>Code Lines</h3>
                        <div class="value text-success">${stats.formatNumber(stats.codeLines)}</div>
                    </div>
                    <div class="card">
                        <h3>Comment Lines</h3>
                        <div class="value text-muted">${stats.formatNumber(stats.commentLines)}</div>
                    </div>
                </div>
            </section>

            <!-- Files by Type -->
            <section aria-labelledby="files-heading">
                <h2 id="files-heading">Files by Type</h2>
                <div class="table-responsive">
                    <table>
                        <thead>
                            <tr>
                                <th scope="col">Extension</th>
                                <th scope="col">Files</th>
                                <th scope="col">Total Lines</th>
                                <th scope="col">Code Lines</th>
                                <th scope="col">% of Codebase</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${stats.formattedFileTypes?.map(type => `
                                <tr>
                                    <td><span class="extension-badge">${type['Extension']}</span></td>
                                    <td>${type['Files']}</td>
                                    <td>${type['Total Lines']}</td>
                                    <td>${type['Code Lines']}</td>
                                    <td>
                                        <div style="display: flex; align-items: center; gap: 12px; width: 100%;">
                                            <div style="flex-grow: 1; height: 8px; background: var(--border); border-radius: 4px; overflow: hidden;">
                                                <div style="height: 100%; width: ${type['% of Codebase']}; background: var(--primary); border-radius: 4px;"></div>
                                            </div>
                                            <span style="font-size: 13px; font-weight: 600; width: 50px; text-align: right;">${type['% of Codebase']}</span>
                                        </div>
                                    </td>
                                </tr>
                            `).join('') || ''}
                        </tbody>
                    </table>
                </div>
            </section>

            ${isSafetyAvailable ? `
                <!-- TypeScript Safety Metrics -->
                <section aria-labelledby="safety-heading">
                    <h2 id="safety-heading">TypeScript Safety</h2>
                    <div class="grid">
                        <div class="card">
                            <h3>Type Coverage</h3>
                            <div class="value">${stats.typescriptSafety!.avgTypeCoverage}%</div>
                            <div class="progress-container">
                                <div class="progress-bar" role="progressbar" aria-valuenow="${typeCoverageVal}" aria-valuemin="0" aria-valuemax="100" aria-label="Type Coverage">
                                    <div class="progress ${typeCoverageClass}" style="width: ${stats.typescriptSafety!.avgTypeCoverage}%"></div>
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <h3>Type Safety Score</h3>
                            <div class="value">${stats.typescriptSafety!.avgTypeSafetyScore}<span style="font-size: 16px; color: var(--text-muted); font-weight: 500;"> / 100</span></div>
                            <div class="progress-container">
                                <div class="progress-bar" role="progressbar" aria-valuenow="${safetyScoreVal}" aria-valuemin="0" aria-valuemax="100" aria-label="Type Safety Score">
                                    <div class="progress ${safetyScoreClass}" style="width: ${stats.typescriptSafety!.avgTypeSafetyScore}%"></div>
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <h3>'any' Type Usage</h3>
                            <div class="value ${stats.typescriptSafety!.totalAnyCount > 10 ? 'text-danger' : 'text-success'}">${stats.formatNumber(stats.typescriptSafety!.totalAnyCount)}</div>
                        </div>
                    </div>
                </section>
            ` : ''}

            ${isComplexityAvailable ? `
                <!-- Code Complexity & Anti-Patterns -->
                <section aria-labelledby="complexity-heading">
                    <h2 id="complexity-heading">Code Complexity</h2>
                    <div class="grid">
                        <div class="card">
                            <h3>Average Complexity</h3>
                            <div class="value ${avgComplexityClass === 'warning' ? 'text-warning' : 'text-success'}">${stats.codeComplexity!.avgComplexity}</div>
                        </div>
                        <div class="card">
                            <h3>Max Complexity</h3>
                            <div class="value ${maxComplexityClass === 'danger' ? 'text-danger' : 'text-success'}">${stats.formatNumber(stats.codeComplexity!.maxComplexity)}</div>
                        </div>
                        <div class="card">
                            <h3>Complex Files</h3>
                            <div class="value ${complexFilesClass === 'danger' ? 'text-danger' : 'text-success'}">${stats.formatNumber(stats.codeComplexity!.complexFiles)}</div>
                        </div>
                    </div>
                </section>

                <section aria-labelledby="smells-heading">
                    <h2 id="smells-heading">Anti-Patterns & Code Smells</h2>
                    <div class="grid">
                        <div class="card">
                            <h3>Callback Hell</h3>
                            <div class="value">${stats.formatNumber(stats.codeComplexity!.codeSmells.callbackHell)}</div>
                            <div style="margin-top: 12px;">
                                <span class="badge ${stats.codeComplexity!.codeSmells.callbackHell > 0 ? 'danger' : 'success'}">
                                    ${stats.codeComplexity!.codeSmells.callbackHell > 0 ? 'Action Needed' : 'Passed'}
                                </span>
                            </div>
                        </div>
                        <div class="card">
                            <h3>God Files (> 500 lines)</h3>
                            <div class="value">${stats.formatNumber(stats.codeComplexity!.codeSmells.godFiles)}</div>
                            <div style="margin-top: 12px;">
                                <span class="badge ${stats.codeComplexity!.codeSmells.godFiles > 0 ? 'danger' : 'success'}">
                                    ${stats.codeComplexity!.codeSmells.godFiles > 0 ? 'Refactor Recommended' : 'Passed'}
                                </span>
                            </div>
                        </div>
                        <div class="card">
                            <h3>Excessive Params (> 4)</h3>
                            <div class="value">${stats.formatNumber(stats.codeComplexity!.codeSmells.excessiveParameters)}</div>
                            <div style="margin-top: 12px;">
                                <span class="badge ${stats.codeComplexity!.codeSmells.excessiveParameters > 0 ? 'danger' : 'success'}">
                                    ${stats.codeComplexity!.codeSmells.excessiveParameters > 0 ? 'Action Needed' : 'Passed'}
                                </span>
                            </div>
                        </div>
                        <div class="card">
                            <h3>Magic Numbers</h3>
                            <div class="value">${stats.formatNumber(stats.codeComplexity!.codeSmells.magicNumbers)}</div>
                            <div style="margin-top: 12px;">
                                <span class="badge ${stats.codeComplexity!.codeSmells.magicNumbers > 0 ? 'warning' : 'success'}">
                                    ${stats.codeComplexity!.codeSmells.magicNumbers > 0 ? 'Review Needed' : 'Passed'}
                                </span>
                            </div>
                        </div>
                        ${stats.codeComplexity!.duplicateCode ? `
                        <div class="card">
                            <h3>Duplicate Code</h3>
                            <div class="value">${stats.formatNumber(stats.codeComplexity!.duplicateCode.totalDuplicateLines)} <span style="font-size: 14px; font-weight: 500; color: var(--text-muted)">lines</span></div>
                            <div style="margin-top: 12px;">
                                <span class="badge ${stats.codeComplexity!.duplicateCode.totalDuplicateLines > 0 ? 'danger' : 'success'}">
                                    ${stats.codeComplexity!.duplicateCode.totalDuplicateLines > 0 ? 'Duplicates Found' : 'Passed'}
                                </span>
                            </div>
                        </div>
                        ` : ''}
                    </div>
                </section>
            ` : ''}
        </main>

        <footer>
            <p>Generated by <a href="https://github.com/amir-valizadeh/ts-analyzer" target="_blank" rel="noopener noreferrer">ts-analyzer</a> &bull; A comprehensive TypeScript static analysis tool</p>
        </footer>
    </div>
</body>
</html>`;
}
