// src/rules-generator.ts
import fs from 'fs/promises';
import path from 'path';
import { ProjectStats } from './index.js';

export interface RulesGeneratorOptions {
    outputFormat?: 'cursorrules' | 'claudeprompt' | 'both';
}

export async function generateRules(projectPath: string, stats: ProjectStats, options: RulesGeneratorOptions = {}): Promise<{
    cursorrulesPath?: string;
    claudepromptPath?: string;
    content: string;
}> {
    const format = options.outputFormat || 'cursorrules';
    
    // Analyze patterns from stats to construct custom rules
    const typeCoverage = stats.typescriptSafety ? parseFloat(stats.typescriptSafety.avgTypeCoverage) : null;
    const safetyScore = stats.typescriptSafety ? stats.typescriptSafety.avgTypeSafetyScore : null;
    const anyCount = stats.typescriptSafety ? stats.typescriptSafety.totalAnyCount : 0;
    const assertionsCount = stats.typescriptSafety ? stats.typescriptSafety.totalAssertions : 0;
    
    const avgComplexity = stats.codeComplexity ? parseFloat(stats.codeComplexity.avgComplexity) : null;
    const maxComplexity = stats.codeComplexity ? stats.codeComplexity.maxComplexity : 0;
    const avgNesting = stats.codeComplexity ? parseFloat(stats.codeComplexity.avgNestingDepth) : null;
    const avgFuncSize = stats.codeComplexity ? parseFloat(stats.codeComplexity.avgFunctionSize) : null;
    
    const callbackHellCount = stats.codeComplexity ? stats.codeComplexity.codeSmells.callbackHell : 0;
    const godFilesCount = stats.codeComplexity ? stats.codeComplexity.codeSmells.godFiles : 0;
    const excessiveParamsCount = stats.codeComplexity ? stats.codeComplexity.codeSmells.excessiveParameters : 0;
    const duplicateLines = stats.codeComplexity && stats.codeComplexity.duplicateCode ? stats.codeComplexity.duplicateCode.totalDuplicateLines : 0;

    // Detect project framework based on file types and dependencies
    let isReact = false;
    let isTypeScript = stats.typescriptSafety && stats.typescriptSafety.tsFileCount > 0;
    
    if (stats.fileTypes['.jsx'] || stats.fileTypes['.tsx']) {
        isReact = true;
    }

    let rulesContent = ``;

    rulesContent += `# AI Coding Rules & Guidelines (Generated by ts-analyzer)\n\n`;
    rulesContent += `This project utilizes strict guidelines to maintain code quality, type safety, and low cyclomatic complexity. Please follow these rules when generating or modifying code.\n\n`;

    rulesContent += `## 1. Project Stack & Architecture\n`;
    rulesContent += `- **Language**: ${isTypeScript ? 'TypeScript' : 'JavaScript (ESNext)'}\n`;
    if (isReact) {
        rulesContent += `- **Framework/UI**: React (Functional components, Hooks, clean separation of concerns)\n`;
    }
    rulesContent += `- **File Extension Rules**: Prefer ${isTypeScript ? '`.ts` (logic) and `.tsx` (components)' : '`.js` and `.jsx`'} for new files.\n\n`;

    rulesContent += `## 2. Type Safety Standards\n`;
    if (isTypeScript) {
        if (safetyScore !== null && safetyScore < 85) {
            rulesContent += `> [!IMPORTANT]\n`;
            rulesContent += `> **Current Project Type Safety Score is ${safetyScore}/100**. We are actively working to raise this score. Do not introduce untyped patterns.\n\n`;
        }
        
        rulesContent += `- **Explicit Type Annotations**: Avoid relying purely on implicit types for public exports, function parameters, and class members.\n`;
        
        if (anyCount > 0) {
            rulesContent += `- **No 'any' Types**: Do NOT use the \`any\` keyword. Use specific types, interfaces, generics, or \`unknown\` if the type is truly dynamic.\n`;
        } else {
            rulesContent += `- **Strict Types**: Maintain our zero-'any' type policy. Do not use the \`any\` keyword.\n`;
        }
        
        if (assertionsCount > 0) {
            rulesContent += `- **Avoid Type Assertions**: Do not use type assertions (\`as Type\` or \`<Type>\`) or non-null assertions (\`!\`) to bypass type-checking. Solve type issues structurally.\n`;
        } else {
            rulesContent += `- **No Assertions**: Avoid raw type assertions or non-null assertions; write proper guard clauses or runtime assertions instead.\n`;
        }
        
        if (typeCoverage !== null) {
            rulesContent += `- **Type Coverage Target**: Ensure all new files have at least **95%** type coverage (current average is **${typeCoverage}%**).\n`;
        }
    } else {
        rulesContent += `- **TypeScript Migration**: Keep in mind that we want to move towards TypeScript. Write JS with clean JSDoc comments where possible to facilitate migration.\n`;
    }
    rulesContent += `\n`;

    rulesContent += `## 3. Code Complexity & Structure\n`;
    if (avgComplexity !== null && avgComplexity > 6) {
        rulesContent += `> [!WARNING]\n`;
        rulesContent += `> **Average Function Cyclomatic Complexity is high (${avgComplexity})**. Focus on simplifying conditionals and splitting logic.\n\n`;
    }

    rulesContent += `- **Keep Functions Small**: Keep functions focused on a single responsibility. Prefer functions under **15** lines of code`;
    if (avgFuncSize !== null) {
        rulesContent += ` (current average is **${avgFuncSize.toFixed(1)}** lines)`;
    }
    rulesContent += `.\n`;

    rulesContent += `- **Nesting Limit**: Do not nest logic blocks (if, for, while, switch) deeper than **3** levels.`;
    if (callbackHellCount > 0 || (avgNesting !== null && avgNesting > 3)) {
        rulesContent += ` (Callback Hell/deep nesting has been flagged in this codebase; avoid adding to it)`;
    }
    rulesContent += `.\n`;

    rulesContent += `- **Limit Function Parameters**: Keep parameter lists to a maximum of **4** variables.`;
    if (excessiveParamsCount > 0) {
        rulesContent += ` (Excessive parameter count has been detected in ${excessiveParamsCount} functions in this codebase)`;
    }
    rulesContent += ` For more parameters, pass an options object or interface.\n`;

    if (godFilesCount > 0) {
        rulesContent += `- **God Files / Size Limit**: Avoid large files. Split code into modules smaller than **500** lines. (Currently there are ${godFilesCount} file(s) exceeding 500 lines).\n`;
    } else {
        rulesContent += `- **File Size Limit**: Keep files under **500** lines of code. Split monolithic modules into smaller modules.\n`;
    }

    if (duplicateLines > 0) {
        rulesContent += `- **DRY Principle (No Clones)**: Extract reusable blocks of logic instead of copying code. Duplicate code lines have been detected in the codebase (${duplicateLines} lines). Refactor into helpers.\n`;
    }
    rulesContent += `\n`;

    rulesContent += `## 4. Best Practices & Quality Checks\n`;
    rulesContent += `- **Anti-Patterns to Avoid**:\n`;
    rulesContent += `  - Magic Numbers: Define constants with descriptive names instead of inline raw values.\n`;
    rulesContent += `  - Nested Ternaries: Use readable if-else blocks or switch statements instead of complex inline ternaries.\n`;
    rulesContent += `  - Re-assigning parameters: Do not modify incoming arguments directly; treat them as immutable.\n`;
    rulesContent += `- **Validation**: Run \`ts-analyzer\` locally to verify your code doesn't decrease the overall Type Safety or Complexity metrics.\n`;

    const results: {
        cursorrulesPath?: string;
        claudepromptPath?: string;
        content: string;
    } = { content: rulesContent };

    if (format === 'cursorrules' || format === 'both') {
        const rulesPath = path.resolve(projectPath, '.cursorrules');
        await fs.writeFile(rulesPath, rulesContent, 'utf8');
        results.cursorrulesPath = rulesPath;
    }
    
    if (format === 'claudeprompt' || format === 'both') {
        const promptPath = path.resolve(projectPath, '.claudeprompt');
        await fs.writeFile(promptPath, rulesContent, 'utf8');
        results.claudepromptPath = promptPath;
    }

    return results;
}
